# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

python:
    - 2.7
#before_script:
#  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install: 
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov
  - pip install numpy
  - pip install scipy
# - python setup.py install
  - pip install codecov
  - pip install -e .
script: 
  - python -m pytest
  - coverage run --source ./ -m py.test

#   - py.test -v cov=./

notifications:
    email: false

after_success:
  - codecov
