# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

python:
    - 2.7
#before_script:
#  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install: 
  - pip install --upgrade pip setuptools
  - pip install pytest pytest-cov
  - pip install numpy
  - pip install scipy
  - python setup.py install
  - pip install codecov
script: 
#  - python -m pytest 
  - py.test -v --cov=code
  

after_success:
  - codecov
