# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

python:
    - 2.7

install:
  - pip install scipy
  - python setup.py install
script: 
  - python -m pytest 
