# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

python:
    - 2.7
#before_script:
#  - export PYTHONPATH=$PYTHONPATH:$(pwd)

install:
  - pip install scipy
  - python setup.py install
  - pip install --user codecov
script: 
  - python -m pytest 

after_success:
  - codecov
